language: java

# only java 8 supported for now
jdk: oraclejdk9

before_install:
  - wget https://services.gradle.org/distributions/gradle-4.2.1-bin.zip
  - unzip -qq gradle-4.2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v


# list dependencies in the install step.
# this forces the check that all dependencies are available
install: gradle dependencies

# run unit tests in main script
script: gradle test
