language: java

# test with java 9 support
jdk: openjdk11

# using the right gradle version
before_install: 
- wget https://services.gradle.org/distributions/gradle-6.2.1-bin.zip 
- unzip -qq gradle-6.2.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-6.2.1
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -v

# list dependencies in the install step.
# this forces the check that all dependencies are available
install: gradle dependencies

# run unit tests in main script
script: gradle test
